openapi: 3.1.0
info:
  title: GhostyLink (Public API)
  description: GhostyLink public API specification
  version: 1.0.0
servers:
  - description: API version 1.0
    url: /api/v1
paths:
  /healthcheck:
    get:
      summary: Check
      description: Check
      responses:
        '200':
          description: Alive
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AliveResponse'
  /secrets:
    get:
      summary: Get secret
      description: Get secret by id
      parameters:
        - name: secretID
          in: query
          required: true
          schema:
            type: string
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetSecretsOut'
    post:
      summary: Create secret
      description: Create secret for given payload
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PostSecretsIn'
      responses:
        '400':
          description: Validation error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationError'
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PostSecretsOut'

components:
  schemas:
    ValidationError:
      type: object
      properties:
        error:
          type: string
      required:
        - error
    GetSecretsOut:
      type: object
      properties:
        payload:
          type: string
          description: Secret payload
      required:
        - payload
    PostSecretsIn:
      type: object
      properties:
        payload:
          type: string
          description: Secret payload
      required:
        - payload
    PostSecretsOut:
      type: object
      properties:
        secretID:
          type: string
          description: Secret ID
      required:
        - secretID
    AliveResponse:
      type: object
      properties:
        text:
          type: string
          description: alive
      required:
        - text