// Package public provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package public

import (
	"github.com/gin-gonic/gin"
)

// AliveResponse defines model for AliveResponse.
type AliveResponse struct {
	// Text alive
	Text string `json:"text"`
}

// SecretsIn defines model for SecretsIn.
type SecretsIn struct {
	// Payload Secret payload
	Payload string `json:"payload"`
}

// SecretsOut defines model for SecretsOut.
type SecretsOut struct {
	// SecretID Secret ID
	SecretID string `json:"secretID"`
}

// ValidationError defines model for ValidationError.
type ValidationError struct {
	Error string `json:"error"`
}

// PostSecretsJSONRequestBody defines body for PostSecrets for application/json ContentType.
type PostSecretsJSONRequestBody = SecretsIn

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Check
	// (GET /healthcheck)
	GetHealthcheck(c *gin.Context)
	// Create secret
	// (POST /secrets)
	PostSecrets(c *gin.Context)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// GetHealthcheck operation middleware
func (siw *ServerInterfaceWrapper) GetHealthcheck(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetHealthcheck(c)
}

// PostSecrets operation middleware
func (siw *ServerInterfaceWrapper) PostSecrets(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostSecrets(c)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/healthcheck", wrapper.GetHealthcheck)
	router.POST(options.BaseURL+"/secrets", wrapper.PostSecrets)
}
