version: "2"

run:
  tests: true
  timeout: 3m

linters:
  default: none
  enable:
    - bodyclose
    - containedctx
    - contextcheck
    - cyclop
    - dupl
    - errcheck
    - forcetypeassert
    - funlen
    - gocognit
    - goconst
    - gocritic
    - gosec
    - govet
    - ineffassign
    - ireturn
    - lll
    - makezero
    - misspell
    - nilerr
    - nilnil
    - noctx
    - nolintlint
    - perfsprint
    - prealloc
    - predeclared
    - reassign
    - revive
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - testifylint
    - tparallel
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - usetesting
    - wastedassign
    - whitespace
    - wrapcheck

  settings:
    cyclop:
      max-complexity: 30
      package-average: 10

    lll:
      line-length: 120
      tab-width: 1

    staticcheck:
      checks: ["all", "-ST1000", "-ST1003", "-ST1016", "-ST1020", "-ST1021", "-ST1022"]

    errcheck:
      check-type-assertions: true

    funlen:
      lines: 150
      statements: 50
      ignore-comments: true

    gocognit:
      min-complexity: 25

    rowserrcheck:
      packages:
        - github.com/jmoiron/sqlx

    revive:
      rules:
        - name: var-naming
          disabled: true

formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports

  settings:
    gci:
      custom-order: true
      sections:
        - standard
        - default
        - localmodule