services:
  valkey:
    image: valkey/valkey:8
    container_name: "dmsecret-valkey-local"
    restart: always
    ports:
      - '6379:6379'
    volumes:
#      - ./valkey.conf:/etc/valkey/valkey.conf
      - valkey:/data

volumes:
  valkey: